name: "zematrack"
services:
  database:
    image: mongo:6.0
    container_name: mongodb-dev
    restart: unless-stopped
    env_file:
      - ./.env
    volumes:
      - zematrack:/data/db
    ports:
      - "27017:27017"
  
  backend:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    env_file:
      - ./.env
    volumes:
      - .:/app
      - /app/node_modules
    depends_on:
      - database
    restart: unless-stopped
    user: "mikiyas"

volumes:
  zematrack:
