name: "zematrack"

services:
  database:
    image: mongo:6.0
    container_name: mongodb
    restart: unless-stopped
    env_file:
      - ./.env
    volumes:
      - zematrack:/data/db

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    env_file:
      - ./.env.production
    depends_on:
      - database
    restart: unless-stopped
    user: "mikiyas"

volumes:
  zematrack:
