name: Deploy ZemaTrack Backend to EC2

on:
  push:
    branches:
      - main
  repository_dispatch:
    types: [deploy_backend]
  workflow_dispatch:

jobs:
  deploy-backend:
    runs-on: ubuntu-latest
    env:
      DEPLOY_DIR: /home/ubuntu/zematrack/zematrack-backend
      APP_NAME: zematrack-backend

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22'

      # Build on GitHub runner 
      - name: Install & Build Project
        run: |
          npm ci
          npm run build

      - name: Setup SSH Agent
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.VPS_SSH_KEY }}

      # Sync files to VPS
      - name: Transfer build Files to VPS
        run: |
          ssh -o StrictHostKeyChecking=no -p ${{ secrets.VPS_PORT }} \
            ${{ secrets.VPS_USER }}@${{ secrets.VPS_HOST }} "mkdir -p ${{env.DEPLOY_DIR}}"
          
          rsync -avz --delete --exclude=".env" -e "ssh -p ${{ secrets.VPS_PORT }}" \
            dist/ package*.json ${{ secrets.VPS_USER }}@${{ secrets.VPS_HOST }}:${{env.DEPLOY_DIR}}

      # Install dependencies on vps & restart via PM2
      - name: Install Dependencies & Restart App
        run: |
          ssh -p ${{ secrets.VPS_PORT }} ${{ secrets.VPS_USER }}@${{ secrets.VPS_HOST }} << EOF
            set -e

            export NVM_DIR="$HOME/.nvm"
            [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
            [ -s "\$NVM_DIR/bash_completion" ] && \. "\$NVM_DIR/bash_completion"

            nvm use 22 || nvm install 22

            cd ${{env.DEPLOY_DIR}}
            echo "Deploying to ${{env.DEPLOY_DIR}}"

            # Install production deps only
            npm ci --omit=dev

            # Restart or start app with PM2
            if pm2 describe ${{ env.APP_NAME }} > /dev/null; then
              pm2 restart ${{ env.APP_NAME }}
            else
              pm2 start server.js --name ${{ env.APP_NAME }}
            fi

            pm2 save
          EOF
